### ISSUE TITLE
select() window freezes when trying to exit on OSX

### ISSUE THREAD

**Issue by willettk** [jaburke166/deepgpet#2]
When running the demo notebook, there is an example and instructions to initialize the GUI window. Left and right clicking work as described in the notebook and saves the selected points to a local file. However, when trying to exit the window (either using esc or enter), the kernel freezes and displays a spinny wheel of death. The only remedy from there is to force quit the kernel (which ends the notebook as well) and restart. 

Setup:

OS: mac Sonoma 14.5
Python 3.10.14
IPython          : 8.25.0
ipykernel        : 6.28.0
ipywidgets       : 8.1.2
jupyter_client   : 8.6.0
jupyter_core     : 5.7.2
jupyter_server   : 2.14.1
jupyterlab       : 4.0.11
nbclient         : 0.8.0
nbconvert        : 7.10.0
nbformat         : 5.9.2
notebook         : 7.0.8
qtconsole        : 5.5.1
traitlets        : 5.14.3

**Comment by jaburke166** [comment]
Hi Kyle,

Thanks for your interest in this repository and method. I've taken a look on my Mac and found a workaround which works for me, which puts `cv2.waitKey(1)` just after `cv2.destroyAllWindows()` in `choseg/metrics/pixel_gui.py`. I'm not entirely sure why this works but apparently there have been similar problems on Linux/OSX systems and openCV (see [here](https://stackoverflow.com/questions/13734276/python-freezes-after-cv2-destroywindow) and [here](https://stackoverflow.com/questions/6116564/destroywindow-does-not-close-window-on-mac-using-python-and-opencv) for more information).

I've tried this on my Mac and seems to work fine. Also tried on my Windows (set up not provided below) and it works too.

Mac Setup:

OS: mac Sonoma 14.6
Python 3.11.8
IPython : 8.22.2
ipykernel : 6.29.3
ipywidgets : 8.1.2
jupyter_client : 8.6.1
jupyter_core : 5.7.2
jupyter_server : 2.13.0
jupyterlab : 4.1.4
nbclient : 0.10.0
nbconvert : 7.16.2
nbformat : 5.10.2
notebook : 7.1.1
qtconsole : n/a
traitlets : 5.14.2

I've created a new branch for this, albeit small, potential fix. See if this works for you and we can merge to main. There has been some discussion online about wrapping `cv2.waitKey(1)` in a for loop, but will cross that bridge if we have to.

Cheers,
Jamie

**Comment by willettk** [comment]
Thanks for looking at this, @jaburke166. I tested your branch using `demo_pixel_gui.ipynb` - this worked in my Mac environment. I was able to save the selected points to the file, and then exiting the GUI window using either **ENTER** or **ESC** closed the window and returned to the notebook. Looks good to me.
